services:
  python:
    build: ./docker
    container_name: python
    volumes:
      - .:/app
      # - ./drl:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 3
              capabilities: [gpu]
